project:
  name: config
  path: /usr/local/var/www/go/src
environment:
  global:
    web:
      debug: true
    nested:
      issue: 24
      nestedText:
        level: 10
        pow: 10
        cool: yes
  prod:
    depends: global
    web:
      debug: false
    custom:
      trololo: -10
      textValuse: some
      textValue: some text
    prodValues:
      values:
        - one
        - two
        - three
      ivalues:
        - 1
        - 2
        - 3
  qa:
    depends: global
  local:
    depends: qa
    custom:
      trololo: -10
      textValuse: some
      textValue: some text
      other: false