project:
  name: config
  path: /usr/local/var/www/go/src
environment:
  global:
    web:
      debug: true
  prod:
    depends: global
    web:
      debug: false
  qa:
    depends: global
  local:
    depends: qa